<?php
if(!defined('ABSPATH'))exit;
function bsktv_admin_columns($columns){$new=array();foreach($columns as $key=>$label){$new[$key]=$label;if($key==='title'){$new['bsktv_status']='狀態';$new['bsktv_verified']='資料確認';$new['bsktv_views']='瀏覽';$new['bsktv_line_clicks']='LINE 點擊';}}return $new;}add_filter('manage_post_posts_columns','bsktv_admin_columns');
function bsktv_admin_column_content($column,$post_id){if($column==='bsktv_status'){$s=get_post_meta($post_id,'bsktv_status',true)?:'active';$map=array('active'=>'營業中','pending'=>'待確認','paused'=>'暫停','closed'=>'歇業');$class='bsktv-status-'.$s;echo '<span class="bsktv-admin-badge '.esc_attr($class).'">'.esc_html($map[$s]??$s).'</span>';}elseif($column==='bsktv_verified'){$verified=get_post_meta($post_id,'bsktv_verified',true)==='1';$date=get_post_meta($post_id,'bsktv_verified_at',true);echo $verified?'<span class="bsktv-verified-yes">✓ 已確認</span>':'<span class="bsktv-verified-no">待確認</span>';if($verified&&$date)echo '<br><small>'.esc_html($date).'</small>';}elseif($column==='bsktv_views'){echo esc_html(number_format_i18n((int)get_post_meta($post_id,'bsktv_views',true)));}elseif($column==='bsktv_line_clicks'){echo esc_html(number_format_i18n((int)get_post_meta($post_id,'bsktv_line_clicks',true)));}}add_action('manage_post_posts_custom_column','bsktv_admin_column_content',10,2);
function bsktv_admin_column_style(){if(!function_exists('get_current_screen'))return;$screen=get_current_screen();if(!$screen||$screen->id!=='edit-post')return;echo '<style>.column-bsktv_status{width:100px}.column-bsktv_verified{width:110px}.column-bsktv_views,.column-bsktv_line_clicks{width:90px}.bsktv-admin-badge{display:inline-block;padding:3px 8px;border-radius:999px;background:#f0f0f1;font-size:12px;font-weight:600}.bsktv-status-active{background:#e7f6ec;color:#176b35}.bsktv-status-pending{background:#fff4d6;color:#815500}.bsktv-status-paused{background:#edf0f2;color:#4d5660}.bsktv-status-closed{background:#f5e8e8;color:#8b2c2c}.bsktv-verified-yes{color:#16803c;font-weight:600}.bsktv-verified-no{color:#8a5a00}</style>';}add_action('admin_head','bsktv_admin_column_style');
function bsktv_admin_sortable_columns($columns){$columns['bsktv_status']='bsktv_status';$columns['bsktv_verified']='bsktv_verified';$columns['bsktv_views']='bsktv_views';$columns['bsktv_line_clicks']='bsktv_line_clicks';return $columns;}add_filter('manage_edit-post_sortable_columns','bsktv_admin_sortable_columns');
function bsktv_admin_orderby_meta($query){if(!is_admin()||!$query->is_main_query())return;$orderby=$query->get('orderby');$map=array('bsktv_status'=>'bsktv_status','bsktv_verified'=>'bsktv_verified','bsktv_views'=>'bsktv_views','bsktv_line_clicks'=>'bsktv_line_clicks');if(isset($map[$orderby])){$query->set('meta_key',$map[$orderby]);$query->set('orderby',in_array($orderby,array('bsktv_status','bsktv_verified'),true)?'meta_value':'meta_value_num');}}add_action('pre_get_posts','bsktv_admin_orderby_meta');
function bsktv_admin_filters(){if(!function_exists('get_current_screen'))return;$screen=get_current_screen();if(!$screen||$screen->id!=='edit-post')return;$status=isset($_GET['bsktv_status_filter'])?sanitize_key(wp_unslash($_GET['bsktv_status_filter'])):'';$verified=isset($_GET['bsktv_verified_filter'])?sanitize_key(wp_unslash($_GET['bsktv_verified_filter'])):'';echo '<select name="bsktv_status_filter"><option value="">全部店家狀態</option>';foreach(array('active'=>'營業中','pending'=>'資料待確認','paused'=>'暫停營業','closed'=>'已歇業') as $key=>$label)echo '<option value="'.esc_attr($key).'" '.selected($status,$key,false).'>'.esc_html($label).'</option>';echo '</select><select name="bsktv_verified_filter"><option value="">全部資料狀態</option><option value="1" '.selected($verified,'1',false).'>已確認</option><option value="0" '.selected($verified,'0',false).'>待確認</option></select>';}add_action('restrict_manage_posts','bsktv_admin_filters');
function bsktv_admin_filter_query($query){if(!is_admin()||!$query->is_main_query()||$query->get('post_type')!=='post')return;$status=isset($_GET['bsktv_status_filter'])?sanitize_key(wp_unslash($_GET['bsktv_status_filter'])):'';$verified=isset($_GET['bsktv_verified_filter'])?sanitize_key(wp_unslash($_GET['bsktv_verified_filter'])):'';$meta=$query->get('meta_query');if(!is_array($meta))$meta=array();if(in_array($status,array('active','pending','paused','closed'),true))$meta[]=array('key'=>'bsktv_status','value'=>$status);if($verified==='1'||$verified==='0')$meta[]=array('key'=>'bsktv_verified','value'=>$verified);if($meta)$query->set('meta_query',$meta);}add_action('pre_get_posts','bsktv_admin_filter_query',20);
