<?php
if(!defined('ABSPATH'))exit;
function bsktv_ajax_check_nonce(){if(!isset($_POST['nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['nonce'])),'bsktv_frontend'))wp_send_json_error(array('message'=>'Invalid request.'),403);}
function bsktv_ajax_store_allowed($post_id){if(get_post_type($post_id)!=='post'||get_post_status($post_id)!=='publish')return false;$status=get_post_meta($post_id,'bsktv_status',true);return $status===''||in_array($status,array('active','pending','paused'),true);}
function bsktv_ajax_store_payload($post_id){$cities=wp_get_post_terms($post_id,'bsktv_city',array('fields'=>'names'));return array('id'=>$post_id,'title'=>get_the_title($post_id),'url'=>get_permalink($post_id),'image'=>get_the_post_thumbnail_url($post_id,'medium_large')?:'','city'=>is_wp_error($cities)?'':implode('、',$cities));}
function bsktv_ajax_favorites(){bsktv_ajax_check_nonce();$ids=isset($_POST['ids'])?(array)wp_unslash($_POST['ids']):array();$ids=array_values(array_unique(array_filter(array_map('absint',$ids))));$ids=array_slice($ids,0,50);$out=array();foreach($ids as $id){if(bsktv_ajax_store_allowed($id))$out[]=bsktv_ajax_store_payload($id);}wp_send_json_success($out);}
add_action('wp_ajax_bsktv_favorites','bsktv_ajax_favorites');add_action('wp_ajax_nopriv_bsktv_favorites','bsktv_ajax_favorites');
function bsktv_ajax_search(){bsktv_ajax_check_nonce();$term=isset($_POST['term'])?sanitize_text_field(wp_unslash($_POST['term'])):'';if(mb_strlen($term,'UTF-8')<2)wp_send_json_success(array());$q=new WP_Query(array('post_type'=>'post','post_status'=>'publish','posts_per_page'=>8,'s'=>$term,'orderby'=>'relevance','no_found_rows'=>true,'ignore_sticky_posts'=>true));$out=array();foreach($q->posts as $post){if(bsktv_ajax_store_allowed($post->ID))$out[]=bsktv_ajax_store_payload($post->ID);}wp_reset_postdata();wp_send_json_success($out);}
add_action('wp_ajax_bsktv_search','bsktv_ajax_search');add_action('wp_ajax_nopriv_bsktv_search','bsktv_ajax_search');
function bsktv_ajax_line_click(){bsktv_ajax_check_nonce();$id=isset($_POST['id'])?absint($_POST['id']):0;if(!$id||!bsktv_ajax_store_allowed($id))wp_send_json_error(array('message'=>'Store not found.'),404);$count=(int)get_post_meta($id,'bsktv_line_clicks',true);update_post_meta($id,'bsktv_line_clicks',$count+1);wp_send_json_success(array('tracked'=>true));}
add_action('wp_ajax_bsktv_line_click','bsktv_ajax_line_click');add_action('wp_ajax_nopriv_bsktv_line_click','bsktv_ajax_line_click');
