<?php
if(!defined('ABSPATH'))exit;
function bsktv_feature_box(){add_meta_box('bsktv_flags','推薦設定','bsktv_flags_render','post','side','default');}add_action('add_meta_boxes','bsktv_feature_box');
function bsktv_flags_render($post){wp_nonce_field('bsktv_flags_save','bsktv_flags_nonce');echo '<p><label><input type="checkbox" name="bsktv_featured" value="1" '.checked(get_post_meta($post->ID,'bsktv_featured',true),'1',false).'> 編輯推薦</label></p><p><label><input type="checkbox" name="bsktv_home_featured" value="1" '.checked(get_post_meta($post->ID,'bsktv_home_featured',true),'1',false).'> 首頁精選</label></p>';}function bsktv_flags_save($id){if(!isset($_POST['bsktv_flags_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['bsktv_flags_nonce'])),'bsktv_flags_save'))return;if(defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE)return;if(wp_is_post_revision($id)||!current_user_can('edit_post',$id))return;update_post_meta($id,'bsktv_featured',isset($_POST['bsktv_featured'])?'1':'0');update_post_meta($id,'bsktv_home_featured',isset($_POST['bsktv_home_featured'])?'1':'0');}add_action('save_post_post','bsktv_flags_save');
function bsktv_track_views(){if(!is_singular('post')||is_admin()||wp_doing_ajax())return;$id=get_queried_object_id();if(!$id)return;update_post_meta($id,'bsktv_views',bsktv_views($id)+1);}add_action('template_redirect','bsktv_track_views');
function bsktv_ajax_search(){check_ajax_referer('bsktv_frontend','nonce');$term=isset($_POST['term'])?sanitize_text_field(wp_unslash($_POST['term'])):'';$city=isset($_POST['city'])?sanitize_title(wp_unslash($_POST['city'])):'';$type=isset($_POST['type'])?sanitize_title(wp_unslash($_POST['type'])):'';$args=array('post_type'=>'post','post_status'=>'publish','posts_per_page'=>12,'s'=>$term);$tax=array('relation'=>'AND');if($city)$tax[]=array('taxonomy'=>'bsktv_city','field'=>'slug','terms'=>$city);if($type)$tax[]=array('taxonomy'=>'bsktv_type','field'=>'slug','terms'=>$type);if(count($tax)>1)$args['tax_query']=$tax;$q=new WP_Query($args);$items=array();while($q->have_posts()){$q->the_post();$items[]=array('id'=>get_the_ID(),'title'=>get_the_title(),'url'=>get_permalink(),'image'=>get_the_post_thumbnail_url(get_the_ID(),'medium'),'city'=>implode('、',wp_get_post_terms(get_the_ID(),'bsktv_city',array('fields'=>'names'))));}wp_reset_postdata();wp_send_json_success($items);}add_action('wp_ajax_bsktv_search','bsktv_ajax_search');add_action('wp_ajax_nopriv_bsktv_search','bsktv_ajax_search');
function bsktv_ajax_favorites(){check_ajax_referer('bsktv_frontend','nonce');$ids=isset($_POST['ids'])?array_map('absint',(array)wp_unslash($_POST['ids'])):array();$ids=array_values(array_filter($ids));if(!$ids){wp_send_json_success(array());}$q=new WP_Query(array('post_type'=>'post','post_status'=>'publish','post__in'=>$ids,'posts_per_page'=>20,'orderby'=>'post__in'));$items=array();while($q->have_posts()){$q->the_post();$items[]=array('id'=>get_the_ID(),'title'=>get_the_title(),'url'=>get_permalink(),'image'=>get_the_post_thumbnail_url(get_the_ID(),'medium'));}wp_reset_postdata();wp_send_json_success($items);}add_action('wp_ajax_bsktv_favorites','bsktv_ajax_favorites');add_action('wp_ajax_nopriv_bsktv_favorites','bsktv_ajax_favorites');
function bsktv_ajax_line_click(){check_ajax_referer('bsktv_frontend','nonce');$id=isset($_POST['id'])?absint($_POST['id']):0;if(!$id||get_post_type($id)!=='post'||get_post_status($id)!=='publish')wp_send_json_error();$n=(int)get_post_meta($id,'bsktv_line_clicks',true)+1;update_post_meta($id,'bsktv_line_clicks',$n);wp_send_json_success(array('clicks'=>$n));}add_action('wp_ajax_bsktv_line_click','bsktv_ajax_line_click');add_action('wp_ajax_nopriv_bsktv_line_click','bsktv_ajax_line_click');
function bsktv_line_clicks($id=null){return (int)get_post_meta($id?:get_the_ID(),'bsktv_line_clicks',true);}
