<?php
if(!defined('ABSPATH'))exit;
function bsktv_store_admin_box(){add_meta_box('bsktv_store_admin','平台管理','bsktv_store_admin_render','post','side','high');}add_action('add_meta_boxes','bsktv_store_admin_box');
function bsktv_store_admin_render($post){wp_nonce_field('bsktv_store_admin_save','bsktv_store_admin_nonce');$status=get_post_meta($post->ID,'bsktv_status',true)?:'active';$verified=get_post_meta($post->ID,'bsktv_verified',true)==='1';$line=get_post_meta($post->ID,'bsktv_line_url_override',true);$date=get_post_meta($post->ID,'bsktv_verified_at',true);echo '<p><label><strong>店家狀態</strong><br><select style="width:100%" name="bsktv_status"><option value="active" '.selected($status,'active',false).'>營業中</option><option value="pending" '.selected($status,'pending',false).'>資料待確認</option><option value="paused" '.selected($status,'paused',false).'>暫停營業</option><option value="closed" '.selected($status,'closed',false).'>已歇業</option></select></label></p>';echo '<p><label><input type="checkbox" name="bsktv_verified" value="1" '.checked($verified,true,false).'> 資料已確認</label></p>';echo '<p><label><strong>店家專屬 LINE 加好友連結</strong><br><input style="width:100%" type="url" name="bsktv_line_url_override" value="'.esc_attr($line).'" placeholder="留空使用全站 LINE" /></label></p>';echo '<p><label><strong>資料確認日期</strong><br><input style="width:100%" type="date" name="bsktv_verified_at" value="'.esc_attr($date).'" /></label></p><p class="description">店家專屬 LINE 留空時，會使用「外觀 → 自訂 → BSKTV 首頁設定」的全站 LINE。</p>';}
function bsktv_store_admin_save($id){if(!isset($_POST['bsktv_store_admin_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['bsktv_store_admin_nonce'])),'bsktv_store_admin_save'))return;if(defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE)return;if(wp_is_post_revision($id)||!current_user_can('edit_post',$id))return;$status=isset($_POST['bsktv_status'])?sanitize_key(wp_unslash($_POST['bsktv_status'])):'active';if(!in_array($status,array('active','pending','paused','closed'),true))$status='active';update_post_meta($id,'bsktv_status',$status);update_post_meta($id,'bsktv_verified',isset($_POST['bsktv_verified'])?'1':'0');$line=isset($_POST['bsktv_line_url_override'])?esc_url_raw(wp_unslash($_POST['bsktv_line_url_override'])):'';if($line)update_post_meta($id,'bsktv_line_url_override',$line);else delete_post_meta($id,'bsktv_line_url_override');$date=isset($_POST['bsktv_verified_at'])?sanitize_text_field(wp_unslash($_POST['bsktv_verified_at'])):'';if($date&&preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))update_post_meta($id,'bsktv_verified_at',$date);else delete_post_meta($id,'bsktv_verified_at');}add_action('save_post_post','bsktv_store_admin_save',20);
function bsktv_store_bulk_actions($actions){$actions['bsktv_status_active']='店家：營業中';$actions['bsktv_status_pending']='店家：待確認';$actions['bsktv_status_paused']='店家：暫停營業';$actions['bsktv_status_closed']='店家：已歇業';$actions['bsktv_verify_yes']='資料：已確認';$actions['bsktv_verify_no']='資料：待確認';return $actions;}add_filter('bulk_actions-edit-post','bsktv_store_bulk_actions');
function bsktv_store_handle_bulk_action($redirect,$action,$post_ids){$status_actions=array('bsktv_status_active'=>'active','bsktv_status_pending'=>'pending','bsktv_status_paused'=>'paused','bsktv_status_closed'=>'closed');$verify_actions=array('bsktv_verify_yes'=>true,'bsktv_verify_no'=>false);$changed=0;if(isset($status_actions[$action])){foreach($post_ids as $post_id){if(get_post_type($post_id)!=='post'||!current_user_can('edit_post',$post_id))continue;update_post_meta($post_id,'bsktv_status',$status_actions[$action]);$changed++;}}elseif(isset($verify_actions[$action])){foreach($post_ids as $post_id){if(get_post_type($post_id)!=='post'||!current_user_can('edit_post',$post_id))continue;$verified=$verify_actions[$action];update_post_meta($post_id,'bsktv_verified',$verified?'1':'0');if($verified)update_post_meta($post_id,'bsktv_verified_at',current_time('Y-m-d'));else delete_post_meta($post_id,'bsktv_verified_at');$changed++;}}if($changed)$redirect=add_query_arg('bsktv_bulk_updated',$changed,$redirect);return $redirect;}add_filter('handle_bulk_actions-edit-post','bsktv_store_handle_bulk_action',10,3);
function bsktv_store_bulk_notice(){if(!isset($_GET['bsktv_bulk_updated']))return;$count=absint($_GET['bsktv_bulk_updated']);if(!$count)return;echo '<div class="notice notice-success is-dismissible"><p>BSKTV 已批次更新 '.esc_html(number_format_i18n($count)).' 間店家。</p></div>';}add_action('admin_notices','bsktv_store_bulk_notice');
function bsktv_store_quick_edit($column_name,$post_type){if($post_type!=='post'||$column_name!=='title')return;echo '<fieldset class="inline-edit-col-right"><div class="inline-edit-col"><label><span class="title">店家狀態</span><select name="bsktv_qe_status"><option value="active">營業中</option><option value="pending">資料待確認</option><option value="paused">暫停營業</option><option value="closed">已歇業</option></select></label><label><input type="checkbox" name="bsktv_qe_verified" value="1"> 資料已確認</label></div></fieldset>';}
add_action('quick_edit_custom_box','bsktv_store_quick_edit',10,2);
function bsktv_store_quick_edit_save($post_id){if(!isset($_POST['bsktv_qe_status'])&&!isset($_POST['bsktv_qe_verified']))return;if(!current_user_can('edit_post',$post_id)||wp_is_post_revision($post_id)||get_post_type($post_id)!=='post')return;if(isset($_POST['bsktv_qe_status'])){$status=sanitize_key(wp_unslash($_POST['bsktv_qe_status']));if(in_array($status,array('active','pending','paused','closed'),true))update_post_meta($post_id,'bsktv_status',$status);}if(isset($_POST['bsktv_qe_verified'])){update_post_meta($post_id,'bsktv_verified','1');update_post_meta($post_id,'bsktv_verified_at',current_time('Y-m-d'));}else{update_post_meta($post_id,'bsktv_verified','0');delete_post_meta($post_id,'bsktv_verified_at');}}
add_action('save_post_post','bsktv_store_quick_edit_save',30);
